<input type="hidden" id="<?php echo $field; ?>" name="<?php echo $field; ?>" value="" />
<div>
    <a href="http://klarna.dev/index.php/admin/payment/update">Update PClasses</a>
</div>
<div>
    <a href="http://klarna.dev/index.php/admin/payment/get">Display PClasses</a>
</div>

<button
    type="button"
    class="scalable save"
    onclick="$('<?php echo $field; ?>').setValue('view');configForm.submit();">
    <span>View PClasses</span>
</button>
<button
    type="button"
    class="scalable save"
    onclick="$('<?php echo $field; ?>').setValue('update');configForm.submit();">
    <span>Update PClasses</span>
</button>
