<ul class="form-list" id="payment_form_<?php print $this->getMethodCode(); ?>" style="display:none;">
    <li>
        <img src="https://cdn.klarna.com/public/images/<?php print $this->getCurrentCountry(); ?>/badges/v1/invoice/<?php print $this->getCurrentCountry(); ?>_invoice_badge_std_blue.png?width=200&eid=<?php print $this->getEid(); ?>" width="100" /><br />
        <input type="text" class="klarna_ssn" id="<?php print $this->getMethodCode(); ?>_ssn" name="payment[<?php print $this->getMethodCode(); ?>_ssn]" class="input-text" value=""/>
        <span class="klarna_box_top_agreement" id="klarna_invoice_terms"></span>
        <script>
            var terms = new Klarna.Terms.Invoice({
                el: 'klarna_invoice_terms',
                eid: '<?php print $this->getEid(); ?>',
                country: '<?php print strtolower($this->getCurrentCountry()); ?>',
                charge: <?php print Mage::helper('klarna')->getConfig('fee', 'invoice'); ?>,
                type: 'desktop'
            });
        </script>
    </li>
</ul>