<ul class="form-list" id="payment_form_<?php print $this->getMethodCode(); ?>" style="display:none;">
    <li>
        <img src="<?php print Mage::helper('klarna')->getPartpaymentLogo(200); ?>" width="100" /><br />
        <input type="hidden" class="klarna_ssn" id="<?php print $this->getMethodCode(); ?>_ssn" name="payment[<?php print $this->getMethodCode(); ?>_ssn]" class="input-text" value=""/>

        <select name="payment[<?php print $this->getMethodCode(); ?>_pclass]">
            <?php foreach ($pclasses as $pclass): ?>
                <option value="<?php print $pclass['id']; ?>"><?php print $pclass['description']; ?> - <?php print $pclass['perMonth']; ?></option>
            <?php endforeach; ?>
        </select>

        <span class="klarna_box_top_agreement" id="klarna_account_terms"></span>
        <script>
            var addressEndpoint = '<?php print $this->getFetchAddressEndpoint(); ?>';
            var updateAddressEndpoint = '<?php print $this->getUpdateAddressEndpoint(); ?>';
            var terms = new Klarna.Terms.Account({
                el: 'klarna_account_terms',
                eid: '<?php print $this->getEid(); ?>',
                country: '<?php print strtolower($this->getCurrentCountry()); ?>',
                charge: 0,
                type: 'desktop'
            });
        </script>
    </li>
</ul>